name: iot_dashboard
description: Campus IoT Monitoring App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  fl_chart: ^0.66.2
  google_fonts: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/iot_logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/iot_logo.png"